spring.application.name=Grace Guide with Inertia.js
management.endpoints.enabled-by-default=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
inertia.enabled=true
# inertia.asset.version=1.0
inertia.manifest.location=classpath:public/dist/.vite/manifest.json